apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - path: collector.yaml
    target:
      group: opentelemetry.io
      version: v1beta1
      kind: OpenTelemetryCollector
      name: compute-node-collector
      namespace: o11y-system
