---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kata-provider-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - compute.datumapis.com
  resources:
  - instances
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - compute.datumapis.com
  resources:
  - instances/finalizers
  verbs:
  - update
- apiGroups:
  - compute.datumapis.com
  resources:
  - instances/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - node.k8s.io
  resources:
  - runtimeclasses
  verbs:
  - get
  - list
  - watch
