apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: kata-provider
    app.kubernetes.io/managed-by: kustomize
  name: kata-provider
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kata-provider-manager-role
subjects:
- kind: ServiceAccount
  name: kata-provider
