//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by defaulter-gen. DO NOT EDIT.

package config

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&KataProvider{}, func(obj interface{}) { SetObjectDefaults_KataProvider(obj.(*KataProvider)) })
	return nil
}

func SetObjectDefaults_KataProvider(in *KataProvider) {
	if in.MetricsServer.BindAddress == "" {
		in.MetricsServer.BindAddress = ":8080"
	}
	if in.WebhookServer.Port == 0 {
		in.WebhookServer.Port = 9443
	}
	if in.DownstreamResourceManagement.RuntimeHandler == "" {
		in.DownstreamResourceManagement.RuntimeHandler = "kata-clh"
	}
}
